services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

        bind:
            $kernelBundles: '%kernel.bundles%'

    whatwedo\TableBundle\:
            resource: '../../*'

    whatwedo\TableBundle\EventListener\DoctrineOrderEventListener:
        tags:
            - { name: kernel.event_listener, event: whatwedo_table.data_load.pre_load, method: orderResultSet, priority: 100 }

    whatwedo\TableBundle\EventListener\FilterEventListener:
        tags:
            - { name: kernel.event_listener, event: whatwedo_table.data_load.pre_load, method: filterResultSet, priority: 100 }

    whatwedo\TableBundle\EventListener\SearchEventListener:
        tags:
            - { name: kernel.event_listener, event: whatwedo_table.data_load.pre_load, method: searchResultSet, priority: 100 }

    whatwedo\TableBundle\EventListener\AjaxFilterSearchListener:
      tags:
            - { name: kernel.event_listener, event: whatwedo_ajax.result_request.filter_set, method: searchResultSet, priority: 100 }
            - { name: kernel.event_listener, event: whatwedo_ajax.result_request.relation_set, method: searchResultSet, priority: 100 }

    whatwedo\TableBundle\Manager\QueryBuilderManager:
        arguments:
            - !tagged_iterator 'query_builder_provider'
